config/routes.rb
Rails.application.routes.draw do

   resources :topics do
     resources :posts, except: [:index]
   end

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  get 'about' => 'welcome#about'

  root to: 'welcome#index'


end

app/models/advertisement.rb
class Advertisement < ActiveRecord::Base
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :topic
	belongs_to :user
	has_many :comments, dependent: :destroy

	 validates :title, length: { minimum: 5 }, presence: true
   validates :body, length: { minimum: 20 }, presence: true
   validates :topic, presence: true
   validates :user, presence: true


end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/models/sponsored_post.rb
class SponsoredPost < ActiveRecord::Base
	belongs_to :topic
end

app/models/topic.rb
class Topic < ActiveRecord::Base
	has_many :posts, dependent: :destroy

	validates :name, length: {minimum: 5}, presence: true
	validates :description, length: {minimum: 15}, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts
	   before_save { self.email = email.downcase }
   EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i


   validates :name, length: { minimum: 1, maximum: 100 }, presence: true

  validates :password, presence: true, length: { minimum: 6 }, if: "password_digest.nil?"
  validates :password, length: { minimum: 6 }, allow_blank: true

   validates :email,
             presence: true,
             uniqueness: { case_sensitive: false },
             length: { minimum: 3, maximum: 100 },
             format: { with: EMAIL_REGEX }


   has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  private
 # #10
   def require_sign_in
     unless current_user
       flash[:error] = "You must be logged in to do that"
 # #11
       redirect_to new_session_path
     end
   end

   
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :require_sign_in, except: :show

  def show
    @post = Post.find(params[:id])
  end

  def new
    @topic = Topic.find(params[:topic_id])
  	@post = Post.new
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = @topic.posts.build(post_params)
    @post.user = current_user

  	if @post.save
  		flash[:notice] = "Post was saved."
  		redirect_to [@topic, @post]
  	else
  		flash[:error] = "There was an error savng the post. Please try again."
  		render :new
  	end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
     @post = Post.find(params[:id])
     @post.assign_attributes(post_params)
 
     if @post.save
       flash[:notice] = "Post was updated."
       redirect_to [@topic, @post]
     else
       flash[:error] = "There was an error saving the post. Please try again."
       render :edit
     end
   end

   def destroy
     @post = Post.find(params[:id])
 
 # #8
     if @post.destroy
       flash[:notice] = "\"#{@post.title}\" was deleted successfully."
       redirect_to @post.topic
     else
       flash[:error] = "There was an error deleting the post."
       render :show
     end
   end

   private
   def post_params
     params.require(:post).permit(:title, :body)
   end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	
	def index
  	@questions = Question.all
  end

  def show
  	@question = Question.find(params[:id])
  end

  def new
  	@question = Question.new
  end

  def create
  	@question = Question.new
  	@question.title = params[:question][:title]
  	@question.body = params[:question][:body]
  	@question.resolved = false

  	if @question.save
  		flash[:notice] = "Question posted!"
  		redirect_to @question
  	else
  		flash[:error] = "Try again."
  		render :new
  	end
  end

  def edit
  	@question = Question.find(params[:id])
  end

  def update
  	@question = Question.new
  	@question.title = params[:question][:title]
  	@question.body = params[:question][:body]
  	@question.resolved = params[:question][:resolved]

  	if @question.save
  		flash[:notice] = "Update successful"
  		redirect_to @question
  	else
  		flash[:error] = "Try again"
  		render :edit
  	end
  end

  def destroy
  	@question = Question.find(params[:id])

  	if @question.destroy
  		flash[:notice] = "#{@question.title} was deleted"
  		redirect_to posts_path
  	else
  		flash[:error] = "Error"
  		render :show
  	end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
  end
 
  def create

    user = User.find_by(email: params[:session][:email].downcase)


    if user && user.authenticate(params[:session][:password])
      create_session user
      flash[:notice] = "Welcome, #{user.name}!"
      redirect_to root_path
    else
      flash[:error] = 'Invalid email/password combination'
      render :new
    end
  end
 
  def destroy
 
    destroy_session(current_user)
    flash[:notice] = "You've been signed out, come back soon!"
    redirect_to root_path
  end


end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
	   def index
     @topics = Topic.all
   end

      def show
     @topic = Topic.find(params[:id])
   end

      def new
     @topic = Topic.new
   end  

      def create
        @topic = Topic.new(topic_params)
 
     if @topic.save
       redirect_to @topic, notice: "Topic was saved successfully."
     else
       flash[:error] = "Error creating topic. Please try again."
       render :new
     end
   end

      def edit
     @topic = Topic.find(params[:id])
   end

   def update
     @topic = Topic.find(params[:id])
     @topic.assign_attributes(topic_params)
 
     if @topic.save
        flash[:notice] = "Topic was updated."
       redirect_to @topic
     else
       flash[:error] = "Error saving topic. Please try again."
       render :edit
     end
   end
   
  def destroy
     @topic = Topic.find(params[:id])
 
     if @topic.destroy
       flash[:notice] = "\"#{@topic.name}\" was deleted successfully."
       redirect_to action: :index
     else
       flash[:error] = "There was an error deleting the topic."
       render :show
     end
   end

   private
   def topic_params
     params.require(:topic).permit(:name, :description, :public)
   end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end

	def create
		@user = User.new 
		 @user.name = params[:user][:name]
     @user.email = params[:user][:email]
     @user.password = params[:user][:password]
     @user.password_confirmation = params[:user][:password_confirmation]
 
 # #10
     if @user.save
       flash[:notice] = "Welcome to Bloccit #{@user.name}!"
       create_session(@user)
       redirect_to root_path
     else
       flash[:error] = "There was an error creating your account. Please try again."
       render :new
     end
   end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def faq
  end
end

app/helpers/advertisement_helper.rb
module AdvertisementHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	 def form_group_tag(errors, &block)
     if errors.any?
       content_tag :div, capture(&block), class: 'form-group has-error'
     else
       content_tag :div, capture(&block), class: 'form-group'
     end
   end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def create_session(user)
     session[:user_id] = user.id
   end
 
 # #5
   def destroy_session(user)
     session[:user_id] = nil
   end
 
 # #6
   def current_user
     User.find_by(id: session[:user_id])
   end

   
    def avatar_url(user)
     gravatar_id = Digest::MD5::hexdigest(user.email).downcase
     "http://gravatar.com/avatar/#{gravatar_id}.png?s=48"
   end
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/posts/_form.html.erb
<%= form_for [topic, post] do |f| %>

   <% if post.errors.any? %>
     <div class="alert alert-danger">
       <h4><%= pluralize(post.errors.count, "error") %>.</h4>
       <ul>
         <% post.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
   <% end %>

   <%= form_group_tag(post.errors[:title]) do %>
     <%= f.label :title %>
     <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
   <% end %>

   <%= form_group_tag(post.errors[:body]) do %>
     <%= f.label :body %>
     <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
   <% end %>
   
   <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
   </div>
 <% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for posts</p>
     <ul>
       <li>Make sure the it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
    <%= render partial: 'form', locals: { topic: @post.topic, post: @post } %>
   </div>
 </div>

app/views/posts/new.html.erb
<h1>New Post</h1>
	<div class="row">

		<div "class=col-md-4">
			<p>Guidelines for posts</p>
			<ul>
				<li>Make sure it rhymes.</li>
				<li>Don't use the letter "A".</li>
				<li>The incessant use of hashtags will get you banned.</li>
			</ul>
		</div>

		<div class="col-mid-8"> 
			<%= render partial: 'form', locals: {topic: @topic, post: @post} %>
		</div>
	</div>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
 
 <div class="row">
   <div class="col-md-8">
     <p><%= @post.body %></p>
   </div>
   <div class="col-md-4">
     <%= link_to "Edit", edit_topic_post_path(@post.topic, @post), class: 'btn btn-success' %>
     <%= link_to "Delete Post", [@post.topic, @post], method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this post?' } %>
   </div>
 </div>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>
 
 <div class="row">
   <div class="col-md-8">
     <%= form_for @question do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
       </div>
       <div class="form-group">
         <%= f.check_box :resolved %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/questions/index.html.erb
<h1>All Questions</h1>
<% @questions.each do |post| %>
	<div class="media">
		<div class="media-body">
			<h4 class ="media-heading">
				<%= link_to post.title, post %>
			</h4>
		</div>
	</div>
<% end %>

app/views/questions/new.html.erb
<h1>New Question</h1>
	<div class="row">
		<div class="col-mid-8"> 
			<%= form_for @question do |f| %>
			
			<div class="form-group">
				<%= f.label :title %>
				<%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
			</div>

			<div class="form-group">
				<%= f.label :body %>
				<%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
			</div>

			<div class="form-group">
				<%= f.submit "Save", class: 'btn btn-success' %>
			</div>

			<% end %>
		</div>
	</div>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
 
 <div class="row">
   <div class="col-md-8">
     <p><%= @question.body %></p>
     <% if @question.resolved %>
     <p><%= "Resolved" %></p>
     <% else %>
     <p><%= "Unresolved" %></p>
     <% end %>
   </div>
   <div class="col-md-4">
     <%= link_to "Edit", edit_question_path(@question), class: 'btn btn-success' %>
      <%= link_to "Delete Question", @question, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this question?'} %>
   </div>
 </div>

app/views/topics/_form.html.erb
<%= form_for topic do |f| %>

   <% if topic.errors.any? %>
     <div class="alert alert-danger">
       <h4><%= pluralize(topic.errors.count, "error") %>.</h4>
       <ul>
         <% topic.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
   <% end %>

   <%= form_group_tag(topic.errors[:name]) do %>
     <%= f.label :name %>
     <%= f.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
   <% end %>

   <%= form_group_tag(topic.errors[:description]) do %>
     <%= f.label :description %>
     <%= f.text_area :description, rows: 8, class: 'form-control', placeholder: "Enter topic description" %>
   <% end %>
   
   <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
   </div>
 <% end %>

app/views/topics/edit.html.erb
<h1>Edit Topic</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for topics:</p>
     <ul>
       <li>Make sure the topic is appropriate.</li>
       <li>Never insult dogs.</li>
       <li>Smile when you type.</li>
     </ul>
   </div>
   <div class="col-md-8">
    <%= render partial: 'form', locals: {topic: @topic} %>
   </div>
 </div>

app/views/topics/index.html.erb
<h1>Topics</h1>
 
 <div class="row">
   <div class="col-md-8">
     <% @topics.each do |topic| %>
       <div class="media">
         <div class="media-body">
           <h4 class="media-heading">
             <%= link_to topic.name, topic %>
           </h4>
           <small>
             <%= topic.description %>
           </small>
         </div>
       </div>
     <% end %>
   </div>
   <div class="col-md-4">
     <%= link_to "New Topic", new_topic_path, class: 'btn btn-success' %>
   </div>
 </div>

app/views/topics/new.html.erb
<h1>New Topic</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for topics:</p>
     <ul>
       <li>Make sure the topic is appropriate.</li>
       <li>Never insult dogs.</li>
       <li>Smile when you type.</li>
     </ul>
   </div>
   <div class="col-md-8">
      <%= render partial: 'form', locals: {topic: @topic} %>
   </div>
 </div>

app/views/topics/show.html.erb
<h1><%= @topic.name %></h1>
 
 <%= link_to "Edit Topic", edit_topic_path, class: 'btn btn-success' %>
 <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %>
 
 <div class="row">
   <div class="col-md-8">
     <p class="lead"><%= @topic.description %></p>
     <% @topic.posts.each do |post| %>
       <div class="media">
         <div class="media-body">
           <h4 class="media-heading">
             <%= link_to post.title, topic_post_path(@topic, post) %>
           </h4>
            <small>
             submitted <%= time_ago_in_words(post.created_at) %> ago <br>
             <%= post.comments.count %> Comments
           </small>
         </div>
       </div>
     <% end %>

     <% @topic.sponsored_posts.each do |sponsored_post| %>
            <div class="media">
         <div class="media-body">
           <h4 class="media-heading">
             <%= link_to sponsored_post.title, topic_sponsored_post_path(@topic, sponsored_post) %>
           </h4>
            <small>
             submitted <%= time_ago_in_words(sponsored_post.created_at) %> ago <br>
           </small>
         </div>
       </div>
     <% end %>


   </div>
   <div class="col-md-4">
     <%= link_to "New Post", new_topic_post_path(@topic), class: 'btn btn-success' %>
     <%= link_to "Delete Topic", @topic, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this topic?' } %>
     <%= link_to "New Sponsored Post", new_topic_sponsored_post_path(@topic), class: 'btn btn-success' %>
   </div>
 </div>

app/views/users/confirm.html.erb
<h1>Sign Up Confirmation</h1>
<h3>Are you sure these values are correct?</h3>

Email: <%= @user.email %>
Name: <%= @user.email %>
<%= button_to "Yes", {:controller => "users", :action => "create", :params => params}, class: 'btn btn-success' %>
<%= link_to "No", {:action => "new"}, class: 'btn btn-danger' %>

app/views/users/new.html.erb
<h2>Sign up</h2>
 
 <div class="row">
   <div class="col-md-8">
     <%= form_for @user, :url => { :action => :confirm } do |f| %>
       <% if @user.errors.any? %>
         <div class="alert alert-danger">
           <h4><%= pluralize(@user.errors.count, "error") %>.</h4>
           <ul>
             <% @user.errors.full_messages.each do |msg| %>
               <li><%= msg %></li>
             <% end %>
           </ul>
         </div>
       <% end %>

       <%= form_group_tag(@user.errors[:name]) do %>
         <%= f.label :name %>
         <%= f.text_field :name, autofocus: true, class: 'form-control', placeholder: "Enter name" %>
       <% end %>
       <%= form_group_tag(@user.errors[:email]) do %>
         <%= f.label :email %>
         <%= f.email_field :email, class: 'form-control', placeholder: "Enter email" %>
       <% end %>
       <%= form_group_tag(@user.errors[:password]) do %>
         <%= f.label :password %>
         <%= f.password_field :password, class: 'form-control', placeholder: "Enter password" %>
       <% end %>
       <%= form_group_tag(@user.errors[:password_confirmation]) do %>
         <%= f.label :password_confirmation %>
         <%= f.password_field :password_confirmation, class: 'form-control', placeholder: "Enter password confirmation" %>
       <% end %>
       <div class="form-group">
         <%= f.submit "Sign up", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>